// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test, console} from "forge-std/Test.sol";
import {Countersign, CountersignCollector} from "../src/Countersign.sol";
import {IX402BatchSettlement, IERC20, ChannelConfig, Voucher, VoucherClaim} from "../src/IX402.sol";

/// Proves that signatures produced by the REAL Rust countersigner are accepted by
/// Coinbase's deployed x402 escrow. Fixture is generated by:
///   cargo run -p countersigner --bin gen_fixture -- <wallet>
contract RustParityTest is Test {
    address constant ESCROW = 0x4020074e9dF2ce1deE5A9C1b5c3f541D02a10003;
    address constant USDC   = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;
    address constant CREATE2 = 0x4e59b44847b379578588920cA78FbF26c0B4956C;
    bytes32 constant SALT = keccak256("countersign.parity.v1");

    IX402BatchSettlement esc = IX402BatchSettlement(ESCROW);
    uint256 rAuthPk = 0xBEEF;
    address constant OWNER = 0x00000000000000000000000000000000000117e5;

    function test_RustSignaturesAcceptedByDeployedEscrow() public {
        vm.createSelectFork(vm.envString("BASE_RPC"), 51777632);

        string memory j = vm.readFile("fixture.json");
        address wallet  = vm.parseJsonAddress(j, ".wallet");
        address seller  = vm.parseJsonAddress(j, ".seller");
        address rAuth   = vm.parseJsonAddress(j, ".receiverAuthorizer");
        address agent   = vm.parseJsonAddress(j, ".agent");
        address oracle  = vm.parseJsonAddress(j, ".oracle");
        uint256 ceiling = vm.parseJsonUint(j, ".ceiling");
        uint256 expiry  = vm.parseJsonUint(j, ".expiry");
        bytes32 rustCid    = vm.parseJsonBytes32(j, ".channelId");
        bytes32 rustDigest = vm.parseJsonBytes32(j, ".digest");
        bytes memory agentSig  = vm.parseJsonBytes(j, ".agentSig");
        bytes memory oracleSig = vm.parseJsonBytes(j, ".oracleSig");

        vm.etch(agent, ""); vm.etch(oracle, ""); vm.etch(rAuth, ""); vm.etch(seller, "");

        // deploy via the REAL canonical CREATE2 deployer, to the address Rust already signed for
        bytes memory initcode = abi.encodePacked(
            type(Countersign).creationCode,
            abi.encode(OWNER, ESCROW, agent, oracle)
        );
        (bool ok,) = CREATE2.call(abi.encodePacked(SALT, initcode));
        require(ok, "create2");
        assertEq(wallet, address(uint160(uint256(keccak256(
            abi.encodePacked(bytes1(0xff), CREATE2, SALT, keccak256(initcode)))))),
            "Rust signed for the CREATE2 address we actually deployed");

        Countersign cs = Countersign(wallet);
        CountersignCollector col = new CountersignCollector();
        deal(USDC, wallet, 50_000_000);
        vm.startPrank(OWNER);
        cs.approveToken(USDC, address(col), type(uint256).max);

        ChannelConfig memory cfg = ChannelConfig({
            payer: wallet, payerAuthorizer: address(0), receiver: seller,
            receiverAuthorizer: rAuth, token: USDC, withdrawDelay: 900,
            salt: bytes32(uint256(1))
        });
        cs.openChannel(cfg, 20_000_000, address(col));
        vm.stopPrank();

        // Rust and Solidity must agree on identity and digest
        bytes32 cid = esc.getChannelId(cfg);
        assertEq(cid, rustCid, "channelId parity: Rust == deployed escrow");
        assertEq(esc.getVoucherDigest(cid, uint128(ceiling)), rustDigest, "voucher digest parity");

        // submit the RUST-PRODUCED signatures to the real contract
        VoucherClaim[] memory rows = new VoucherClaim[](1);
        rows[0] = VoucherClaim({
            voucher: Voucher({channel: cfg, maxClaimableAmount: uint128(ceiling)}),
            signature: abi.encode(agentSig, oracleSig, seller, uint64(expiry)),
            totalClaimed: uint128(ceiling)
        });
        bytes memory batchSig;
        {
            (uint8 v, bytes32 r, bytes32 s) = vm.sign(rAuthPk, esc.getClaimBatchDigest(rows));
            batchSig = abi.encodePacked(r, s, v);
        }

        uint256 snap = vm.snapshotState();

        // --- 1. clean path: Rust signatures are accepted by Coinbase's escrow ---
        esc.claimWithSignature(rows, batchSig);
        (, uint128 claimed) = esc.channels(cid);
        assertEq(claimed, ceiling, "escrow accepted the Rust-signed voucher");
        esc.settle(seller, USDC);
        assertEq(IERC20(USDC).balanceOf(seller), ceiling, "seller paid from Rust-produced signatures");
        console.log("PASS: Rust-signed voucher accepted by deployed escrow. USDC paid:", uint256(claimed));

        // --- 2. same signatures, but revoked first: settlement-time kill switch ---
        vm.revertToState(snap);
        vm.prank(oracle);
        cs.revoke(seller, 2); // 2 = known_scammer
        vm.expectRevert();
        esc.claimWithSignature(rows, batchSig);
        (, uint128 afterRevoke) = esc.channels(cid);
        assertEq(afterRevoke, 0, "identical Rust signatures are worthless once the seller is revoked");
        console.log("PASS: revocation invalidates already-signed Rust vouchers");
    }
}
